### PR TITLE
Added Image Background Selector

### PR DESCRIPTION
**Pull request by ImArnoldDCODES**
Screenshot 2024-12-14 115020

### CODE REVIEW

**Comment by heyrapto** [comment]
needs fix look into it please

**Comment by heyrapto** [comment]
Has conflicts

**Comment by ImArnoldDCODES** [comment]
> Has conflicts

i made the pr weeks ago, have you updated your env?

I'll update the branch though

**Comment by heyrapto** [comment]
I have updated the env files and added it in .gitignore, you can fork the project again and copy paste the logic code

**Comment by ImArnoldDCODES** [comment]
@heycalebszn check it out

**Comment by heyrapto** [comment]
Merged try it out and see if it works as expected

**Pull request merged**
